name: validate SVG
on:
 workflow_dispatch:
 pull_request:
  paths:
   - "**.svg"
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
 validate:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: checkout dtd-xml-validator repo
     uses: actions/checkout@v5
     with:
      repository: dujanhung/dtd-xml-validator
      path: dtd-xml-validator
   - name: checkout dtd repo
     uses: actions/checkout@v5
     with:
      repository: dujanhung/dtd
      path: dtd
   - name: setup Python
     uses: actions/setup-python@v6
     with:
      python-version: '3.14'
   - name: install lxml
     run: pip install lxml
   - name: validate
     run: |
      find . -type f -name "*.svg" -exec python dtd-xml-validator/script.py dtd/files/default/svg.dtd {} svg \;